import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Main from "./components/main/page";
import Home from "./components/Home/home";
import MyWorks from "./components/mywork/page";
import Skills from "./components/skills/page";
import Navbar from "./components/navbar/page";
import Intro from "./components/Introduction/Intro";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body className="min-h-full flex flex-col">
        <Navbar />

        <div className="ml-56 w-[calc(100%-14rem)] max-md:ml-0 max-md:w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
